version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: ghost-nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/ssl/yourhost.xyz.key:/etc/nginx/yourhost.xyz.key:ro
      - ./nginx/ssl/yourhost.xyz.crt:/etc/nginx/yourhost.xyz.crt:ro
      - ./nginx/conf/ghost.conf:/etc/nginx/conf.d/ghost.conf:z
    links:
      - ghost
    restart: always

  ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    volumes:
      - $PWD/ghost/volumes/config.production.json:/var/lib/ghost/config.production.json:z #overwrite default settings 
      - ./ghost/content:/var/lib/ghost/content:z
    expose:
    - "3306"
    environment: # this section can be commented to start in dev mode by default
      - NODE_ENV=production # set either production or development, then it will load the respective config
    restart: always
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
       - ./dbdata:/var/lib/mysql:z  # Persist storage
    expose:
      - "3306"
    environment:
      # Beware of special characters in password that can be interpreted by shell
      - MYSQL_ROOT_PASSWORD= #specify your root pass
      - MYSQL_DATABASE=ghostdata
      - MYSQL_USER=ghostusr
      - MYSQL_PASSWORD= xyx #please change this
    restart: always